include:
  # VALIDATE
  - project: crypdefi/pipelinetemplates
    file: validate/.check-version-pre-merge.yml
    inputs:
      read_version: $(grep '"version"=' cargo.toml | awk -F'"' '{print $4}')



stages:
  - validate
  - build

cargo-check:
  stage: validate
  image: rust:latest
  script:
    - cargo check

cargo-build-release:
  stage: build
  image: rust:latest
  script:
    - cargo build --release

uniffi_python_binding:
  stage: build
  image: rust:latest
  script:
    - cargo run --bin uniffi-bindgen generate --library target/release/libcrypdefi_bot_sdk.so --language python --out-dir python-sdk
  needs: ["cargo-build-release"]
  artifacts:
    paths:
      - python-sdk/

go_binding:
  stage: build
  image: rust:latest
  before_script:
    # Install uniffi-bindgen-go if not already in your image
    - cargo install uniffi-bindgen-go
  script:
    - uniffi-bindgen-go --library target/release/libcrypdefi_bot_sdk.so --out-dir go-sdk
  needs: ["cargo-build-release"]
  artifacts:
    paths:
      - go-sdk/

cache:
  key: "${CI_COMMIT_REF_SLUG}"
  paths:
    - target/
    - .cargo/registry/
    - .cargo/git/
