[package]
name = "crypdefi-bot-sdk"
version = "0.1.7"
edition = "2024"
exclude = [
    "python-sdk",
    "go-sdk",
]
description="SDK for using BOTs with the crypdefi backend"
license-file = "MIT-CC"

[dependencies]
p256 = "0.13.2"
pkcs8 = { version ="0.10.2", features = ["pem", "std"] }
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1.0.219", features = ["serde_derive"] }
thiserror = "2.0.12"
tokio = { version = "1", features = ["full"] }
pem = "3.0.5"
sha2 = "0.10.8"
hex = "0.4.3"
serde_json = "1.0.140"

[lib]
name = "crypdefi_bot_sdk"
path = "src/lib.rs"


[[bin]]
name = "crypdefi-bot"
path = "src/bot.rs"


[lints.rust]
unreachable_pub = "warn"
unused_must_use = "deny"
rust_2018_idioms = { level = "deny", priority = -1 }

[lints.clippy]
cognitive_complexity = "warn"
collection_is_never_read = "warn"
fallible_impl_from = "warn"
manual_clamp = "warn"
missing_const_for_fn = "warn"
mutex_integer = "warn"
redundant_clone = "warn"
unwrap_used = "deny"
implicit_return = "allow"
